#installation d'Apache sur le serveur de développement
- name: "Installation d'Apache"
  hosts: all
  tasks:
      - name: Inscrire le nouveau dépôt
        apt_repository:
           repo: deb http://ftp.fr.debian.org/debian/ stretch main
           state: present
           update_cache: yes
         
      - name: Installation d'apache2 
        apt:
          name: apache2,ca-certificates,apt-transport-https
          state: present 
        
      - name: Démarrer le service Apache
        service:
          name: apache2
          state: started
          enabled: yes
        
      - name: Enregistrer une clé
        apt_key:
          url: https://packages.sury.org/php/apt.gpg
          state: present
        
      - name: Installation 
        apt_repository :
          repo : deb https://packages.sury.org/php/ stretch main
          state: present
          update_cache: yes
        
      - name : Installation de PHP7
        apt :  
          name : php7.2
          state : present
        
- name: Installation de MySql
  hosts: all
  tasks:
         
      - name: Installer de python pip
        apt:
          name: python-pip
          state: present 
        
      - name: Installer le module Python pour Mysql
        pip:
          name: PyMySQL
        
      - name: Installation de python-mysqldb, mysqlserveur
        apt:
          name: python-mysqldb,mysql-server
          state: present 
      
      - name: Création d'une base de données    
        mysql_db:    
          name: "{{mysql_db}}"
          state: present  
          login_unix_socket: /var/run/mysqld/mysqld.sock  
      
      - name: Création de l'utilisateur eleve et affectation des privilèges sur une base de données
        mysql_user:
          name: "{{mysql_user}}"
          password: "{{mysql_password}}"
          host: localhost
          priv: "{{mysql_db}}.*:ALL,GRANT"
          login_unix_socket: /var/run/mysqld/mysqld.sock
        
- name: PHPMYADMIN Installation
  hosts: all
  tasks:   
     
      - name: Installation de debconf-utils
        apt:
          name: debconf-utils
          state: present 
      
      - name: Installation de dbconfig
        debconf: 
           name: phpmyadmin 
           question: phpmyadmin/dbconfig-install 
           value: true 
           vtype: boolean
          
           question: phpmyadmin/app-password-confirm
           value: btsinfo 
           vtype: password
          
       
           question: phpmyadmin/mysql/admin-pass
           value: btsinfo 
           vtype: password
          
        
           question: phpmyadmin/mysql/app-pass
           value: btsinfo 
           vtype: password
          
        
           question: phpmyadmin/reconfigure-webserver
           value: apache2 
           vtype: multiselect          
          
      - name: Installation PhpMyAdmin
        apt:
          name: phpmyadmin
          state: present
          
- name: Gestion des erreurs
  hosts: all
  tasks: 
      
      - name: Suppression index.html
        file: 
          path: /var/www/html/index.html
          state: absent   
        
      - name: Gestion du index.php
        copy:
          src: /root/index.php
          dest: /var/www/html/
          owner: www-data
          group: www-data
          mode: 0755     
          
      - name: Activation de l'affichage des erreurs display_errors
        lineinfile:
          dest: /etc/php/7.2/apache2/php.ini
          regexp: '^display_errors = Off'
          line: 'display_errors = On'
          
      - name: Activation de l'affichage des erreurs display_startup_errors
        lineinfile:
          dest: /etc/php/7.2/apache2/php.ini
          regexp: '^display_startup_errors = Off'
          line: 'display_startup_errors = On'